//
// File generated by rootcint at Sun Jul 31 13:27:18 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIhomedIirisdImholldItreeIrisdIdOdOdItreeIrisdIlibdITEventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TEventDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TEvent(void *p = 0);
   static void *newArray_TEvent(Long_t size, void *p);
   static void delete_TEvent(void *p);
   static void deleteArray_TEvent(void *p);
   static void destruct_TEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TEvent*)
   {
      ::TEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TEvent", ::TEvent::Class_Version(), "/home/iris/mholl/treeIris/../treeIris/include/TEvent.h", 20,
                  typeid(::TEvent), DefineBehavior(ptr, ptr),
                  &::TEvent::Dictionary, isa_proxy, 4,
                  sizeof(::TEvent) );
      instance.SetNew(&new_TEvent);
      instance.SetNewArray(&newArray_TEvent);
      instance.SetDelete(&delete_TEvent);
      instance.SetDeleteArray(&deleteArray_TEvent);
      instance.SetDestructor(&destruct_TEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TEvent*)
   {
      return GenerateInitInstanceLocal((::TEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void IDet_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_IDet(void *p = 0);
   static void *newArray_IDet(Long_t size, void *p);
   static void delete_IDet(void *p);
   static void deleteArray_IDet(void *p);
   static void destruct_IDet(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::IDet*)
   {
      ::IDet *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::IDet >(0);
      static ::ROOT::TGenericClassInfo 
         instance("IDet", ::IDet::Class_Version(), "/home/iris/mholl/treeIris/../treeIris/include/IDet.h", 9,
                  typeid(::IDet), DefineBehavior(ptr, ptr),
                  &::IDet::Dictionary, isa_proxy, 4,
                  sizeof(::IDet) );
      instance.SetNew(&new_IDet);
      instance.SetNewArray(&newArray_IDet);
      instance.SetDelete(&delete_IDet);
      instance.SetDeleteArray(&deleteArray_IDet);
      instance.SetDestructor(&destruct_IDet);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::IDet*)
   {
      return GenerateInitInstanceLocal((::IDet*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::IDet*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void ITdc_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ITdc(void *p = 0);
   static void *newArray_ITdc(Long_t size, void *p);
   static void delete_ITdc(void *p);
   static void deleteArray_ITdc(void *p);
   static void destruct_ITdc(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ITdc*)
   {
      ::ITdc *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ITdc >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ITdc", ::ITdc::Class_Version(), "/home/iris/mholl/treeIris/../treeIris/include/ITdc.h", 9,
                  typeid(::ITdc), DefineBehavior(ptr, ptr),
                  &::ITdc::Dictionary, isa_proxy, 4,
                  sizeof(::ITdc) );
      instance.SetNew(&new_ITdc);
      instance.SetNewArray(&newArray_ITdc);
      instance.SetDelete(&delete_ITdc);
      instance.SetDeleteArray(&deleteArray_ITdc);
      instance.SetDestructor(&destruct_ITdc);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ITdc*)
   {
      return GenerateInitInstanceLocal((::ITdc*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ITdc*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TEvent::Class_Name()
{
   return "TEvent";
}

//______________________________________________________________________________
const char *TEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *IDet::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *IDet::Class_Name()
{
   return "IDet";
}

//______________________________________________________________________________
const char *IDet::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::IDet*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int IDet::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::IDet*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void IDet::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::IDet*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *IDet::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::IDet*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *ITdc::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *ITdc::Class_Name()
{
   return "ITdc";
}

//______________________________________________________________________________
const char *ITdc::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ITdc*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ITdc::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ITdc*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ITdc::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ITdc*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ITdc::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ITdc*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class TEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(TEvent::Class(),this);
   }
}

//______________________________________________________________________________
void TEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TEvent.
      TClass *R__cl = ::TEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fThetacm", &fThetacm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fLP", &fLP);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fHP", &fHP);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQv", &fQv);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEB", &fEB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRun", &fRun);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TEvent(void *p) {
      return  p ? new(p) ::TEvent : new ::TEvent;
   }
   static void *newArray_TEvent(Long_t nElements, void *p) {
      return p ? new(p) ::TEvent[nElements] : new ::TEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_TEvent(void *p) {
      delete ((::TEvent*)p);
   }
   static void deleteArray_TEvent(void *p) {
      delete [] ((::TEvent*)p);
   }
   static void destruct_TEvent(void *p) {
      typedef ::TEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TEvent

//______________________________________________________________________________
void IDet::Streamer(TBuffer &R__b)
{
   // Stream an object of class IDet.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(IDet::Class(),this);
   } else {
      R__b.WriteClassBuffer(IDet::Class(),this);
   }
}

//______________________________________________________________________________
void IDet::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class IDet.
      TClass *R__cl = ::IDet::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdMul", &TYdMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdChannel", (void*)&TYdChannel);
      R__insp.InspectMember("vector<Int_t>", (void*)&TYdChannel, "TYdChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdEnergy", (void*)&TYdEnergy);
      R__insp.InspectMember("vector<Double_t>", (void*)&TYdEnergy, "TYdEnergy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdADC", (void*)&TYdADC);
      R__insp.InspectMember("vector<Int_t>", (void*)&TYdADC, "TYdADC.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdNo", (void*)&TYdNo);
      R__insp.InspectMember("vector<Int_t>", (void*)&TYdNo, "TYdNo.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdRing", (void*)&TYdRing);
      R__insp.InspectMember("vector<Int_t>", (void*)&TYdRing, "TYdRing.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdTheta", (void*)&TYdTheta);
      R__insp.InspectMember("vector<Double_t>", (void*)&TYdTheta, "TYdTheta.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TCsI1Mul", &TCsI1Mul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TCsI1Channel", (void*)&TCsI1Channel);
      R__insp.InspectMember("vector<Int_t>", (void*)&TCsI1Channel, "TCsI1Channel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TCsI1Energy", (void*)&TCsI1Energy);
      R__insp.InspectMember("vector<Double_t>", (void*)&TCsI1Energy, "TCsI1Energy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TCsI1ADC", (void*)&TCsI1ADC);
      R__insp.InspectMember("vector<Double_t>", (void*)&TCsI1ADC, "TCsI1ADC.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TCsI2Mul", &TCsI2Mul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TCsI2Channel", (void*)&TCsI2Channel);
      R__insp.InspectMember("vector<Int_t>", (void*)&TCsI2Channel, "TCsI2Channel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TCsI2Energy", (void*)&TCsI2Energy);
      R__insp.InspectMember("vector<Double_t>", (void*)&TCsI2Energy, "TCsI2Energy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TCsI2ADC", (void*)&TCsI2ADC);
      R__insp.InspectMember("vector<Double_t>", (void*)&TCsI2ADC, "TCsI2ADC.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SSB", &SSB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TICChannel", &TICChannel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TICEnergy", &TICEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TIC[16]", TIC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1rMul", &TSd1rMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1rChannel", (void*)&TSd1rChannel);
      R__insp.InspectMember("vector<Int_t>", (void*)&TSd1rChannel, "TSd1rChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1rEnergy", (void*)&TSd1rEnergy);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd1rEnergy, "TSd1rEnergy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1rADC", (void*)&TSd1rADC);
      R__insp.InspectMember("vector<Int_t>", (void*)&TSd1rADC, "TSd1rADC.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1sMul", &TSd1sMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1sChannel", (void*)&TSd1sChannel);
      R__insp.InspectMember("vector<Int_t>", (void*)&TSd1sChannel, "TSd1sChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1sEnergy", (void*)&TSd1sEnergy);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd1sEnergy, "TSd1sEnergy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1sADC", (void*)&TSd1sADC);
      R__insp.InspectMember("vector<Int_t>", (void*)&TSd1sADC, "TSd1sADC.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2rMul", &TSd2rMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2rChannel", (void*)&TSd2rChannel);
      R__insp.InspectMember("vector<Int_t>", (void*)&TSd2rChannel, "TSd2rChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2rEnergy", (void*)&TSd2rEnergy);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd2rEnergy, "TSd2rEnergy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2rADC", (void*)&TSd2rADC);
      R__insp.InspectMember("vector<Int_t>", (void*)&TSd2rADC, "TSd2rADC.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2rEnergyCal", &TSd2rEnergyCal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2sMul", &TSd2sMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2sChannel", (void*)&TSd2sChannel);
      R__insp.InspectMember("vector<Int_t>", (void*)&TSd2sChannel, "TSd2sChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2sEnergy", (void*)&TSd2sEnergy);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd2sEnergy, "TSd2sEnergy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2sADC", (void*)&TSd2sADC);
      R__insp.InspectMember("vector<Int_t>", (void*)&TSd2sADC, "TSd2sADC.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSdETot", &TSdETot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSdTheta", (void*)&TSdTheta);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSdTheta, "TSdTheta.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSdThetaCM", &TSdThetaCM);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSdPhi", (void*)&TSdPhi);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSdPhi, "TSdPhi.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QValue", &QValue);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TBE", &TBE);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_IDet(void *p) {
      return  p ? new(p) ::IDet : new ::IDet;
   }
   static void *newArray_IDet(Long_t nElements, void *p) {
      return p ? new(p) ::IDet[nElements] : new ::IDet[nElements];
   }
   // Wrapper around operator delete
   static void delete_IDet(void *p) {
      delete ((::IDet*)p);
   }
   static void deleteArray_IDet(void *p) {
      delete [] ((::IDet*)p);
   }
   static void destruct_IDet(void *p) {
      typedef ::IDet current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::IDet

//______________________________________________________________________________
void ITdc::Streamer(TBuffer &R__b)
{
   // Stream an object of class ITdc.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(ITdc::Class(),this);
   } else {
      R__b.WriteClassBuffer(ITdc::Class(),this);
   }
}

//______________________________________________________________________________
void ITdc::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ITdc.
      TClass *R__cl = ::ITdc::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TICTMul", &TICTMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TICTChannel", (void*)&TICTChannel);
      R__insp.InspectMember("vector<Double_t>", (void*)&TICTChannel, "TICTChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TICTime", (void*)&TICTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&TICTime, "TICTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TICTimeRF", (void*)&TICTimeRF);
      R__insp.InspectMember("vector<Double_t>", (void*)&TICTimeRF, "TICTimeRF.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdTMul", &TYdTMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdTChannel", (void*)&TYdTChannel);
      R__insp.InspectMember("vector<Double_t>", (void*)&TYdTChannel, "TYdTChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdTime", (void*)&TYdTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&TYdTime, "TYdTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYdTimeRF", (void*)&TYdTimeRF);
      R__insp.InspectMember("vector<Double_t>", (void*)&TYdTimeRF, "TYdTimeRF.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYuTMul", &TYuTMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYuTChannel", (void*)&TYuTChannel);
      R__insp.InspectMember("vector<Double_t>", (void*)&TYuTChannel, "TYuTChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYuTime", (void*)&TYuTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&TYuTime, "TYuTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TYuTimeRF", (void*)&TYuTimeRF);
      R__insp.InspectMember("vector<Double_t>", (void*)&TYuTimeRF, "TYuTimeRF.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSurTMul", &TSurTMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSurTChannel", (void*)&TSurTChannel);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSurTChannel, "TSurTChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSurTime", (void*)&TSurTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSurTime, "TSurTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSurTimeRF", (void*)&TSurTimeRF);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSurTimeRF, "TSurTimeRF.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSusTMul", &TSusTMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSusTChannel", (void*)&TSusTChannel);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSusTChannel, "TSusTChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSusTime", (void*)&TSusTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSusTime, "TSusTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSusTimeRF", (void*)&TSusTimeRF);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSusTimeRF, "TSusTimeRF.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1rTMul", &TSd1rTMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1rTChannel", (void*)&TSd1rTChannel);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd1rTChannel, "TSd1rTChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1rTime", (void*)&TSd1rTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd1rTime, "TSd1rTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1rTimeRF", (void*)&TSd1rTimeRF);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd1rTimeRF, "TSd1rTimeRF.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1sTMul", &TSd1sTMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1sTChannel", (void*)&TSd1sTChannel);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd1sTChannel, "TSd1sTChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1sTime", (void*)&TSd1sTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd1sTime, "TSd1sTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd1sTimeRF", (void*)&TSd1sTimeRF);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd1sTimeRF, "TSd1sTimeRF.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2rTMul", &TSd2rTMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2rTChannel", (void*)&TSd2rTChannel);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd2rTChannel, "TSd2rTChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2rTime", (void*)&TSd2rTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd2rTime, "TSd2rTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2rTimeRF", (void*)&TSd2rTimeRF);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd2rTimeRF, "TSd2rTimeRF.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2sTMul", &TSd2sTMul);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2sTChannel", (void*)&TSd2sTChannel);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd2sTChannel, "TSd2sTChannel.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2sTime", (void*)&TSd2sTime);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd2sTime, "TSd2sTime.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TSd2sTimeRF", (void*)&TSd2sTimeRF);
      R__insp.InspectMember("vector<Double_t>", (void*)&TSd2sTimeRF, "TSd2sTimeRF.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ITdc(void *p) {
      return  p ? new(p) ::ITdc : new ::ITdc;
   }
   static void *newArray_ITdc(Long_t nElements, void *p) {
      return p ? new(p) ::ITdc[nElements] : new ::ITdc[nElements];
   }
   // Wrapper around operator delete
   static void delete_ITdc(void *p) {
      delete ((::ITdc*)p);
   }
   static void deleteArray_ITdc(void *p) {
      delete [] ((::ITdc*)p);
   }
   static void destruct_ITdc(void *p) {
      typedef ::ITdc current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::ITdc

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

namespace ROOT {
   void vectorlEintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEintgR_Dictionary();
   static void *new_vectorlEintgR(void *p = 0);
   static void *newArray_vectorlEintgR(Long_t size, void *p);
   static void delete_vectorlEintgR(void *p);
   static void deleteArray_vectorlEintgR(void *p);
   static void destruct_vectorlEintgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<int>*)
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<int>", -2, "prec_stl/vector", 49,
                  typeid(vector<int>), DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEintgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
   static void *newArray_vectorlEintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEintgR(void *p) {
      delete ((vector<int>*)p);
   }
   static void deleteArray_vectorlEintgR(void *p) {
      delete [] ((vector<int>*)p);
   }
   static void destruct_vectorlEintgR(void *p) {
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<int>

/********************************************************
* /home/iris/mholl/treeIris/../treeIris/lib/TEventDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTEventDict();

extern "C" void G__set_cpp_environmentTEventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/iris/mholl/treeIris/../treeIris/include/TEvent.h");
  G__add_compiledheader("/home/iris/mholl/treeIris/../treeIris/include/IDet.h");
  G__add_compiledheader("/home/iris/mholl/treeIris/../treeIris/include/ITdc.h");
  G__cpp_reset_tagtableTEventDict();
}
#include <new>
extern "C" int G__cpp_dllrevTEventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TEvent */
static int G__TEventDict_548_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TEvent[n];
     } else {
       p = new((void*) gvp) TEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TEvent;
     } else {
       p = new((void*) gvp) TEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TEventDictLN_TEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TEvent((Int_t) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TEvent((Int_t) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TEventDictLN_TEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TEvent(*(TEvent*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) TEvent(*(TEvent*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TEventDictLN_TEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TEvent*) G__getstructoffset())->Calculate());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TEvent*) G__getstructoffset())->Clear());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_548_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TEvent G__TTEvent;
static int G__TEventDict_548_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TEvent*) (soff+(sizeof(TEvent)*i)))->~G__TTEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TEvent*) (soff))->~G__TTEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TEventDict_548_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TEvent* dest = (TEvent*) G__getstructoffset();
   *dest = *(TEvent*) libp->para[0].ref;
   const TEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* IDet */
static int G__TEventDict_549_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   IDet* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new IDet[n];
     } else {
       p = new((void*) gvp) IDet[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new IDet;
     } else {
       p = new((void*) gvp) IDet;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TEventDictLN_IDet));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IDet*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) IDet::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) IDet::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) IDet::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      IDet::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IDet*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) IDet::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) IDet::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) IDet::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_549_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) IDet::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TEventDict_549_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   IDet* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new IDet(*(IDet*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TEventDictLN_IDet));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef IDet G__TIDet;
static int G__TEventDict_549_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (IDet*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((IDet*) (soff+(sizeof(IDet)*i)))->~G__TIDet();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (IDet*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((IDet*) (soff))->~G__TIDet();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TEventDict_549_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   IDet* dest = (IDet*) G__getstructoffset();
   *dest = *(IDet*) libp->para[0].ref;
   const IDet& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* ITdc */
static int G__TEventDict_554_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ITdc* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ITdc[n];
     } else {
       p = new((void*) gvp) ITdc[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ITdc;
     } else {
       p = new((void*) gvp) ITdc;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TEventDictLN_ITdc));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ITdc*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ITdc::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ITdc::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ITdc::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ITdc::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ITdc*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ITdc::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ITdc::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ITdc::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TEventDict_554_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ITdc::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TEventDict_554_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ITdc* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ITdc(*(ITdc*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TEventDictLN_ITdc));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ITdc G__TITdc;
static int G__TEventDict_554_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ITdc*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ITdc*) (soff+(sizeof(ITdc)*i)))->~G__TITdc();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ITdc*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ITdc*) (soff))->~G__TITdc();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TEventDict_554_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ITdc* dest = (ITdc*) G__getstructoffset();
   *dest = *(ITdc*) libp->para[0].ref;
   const ITdc& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TEvent */

/* IDet */

/* ITdc */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTEventDict {
 public:
  G__Sizep2memfuncTEventDict(): p(&G__Sizep2memfuncTEventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTEventDict::*p)();
};

size_t G__get_sizep2memfuncTEventDict()
{
  G__Sizep2memfuncTEventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTEventDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TEventDictLN_TEvent))) {
     TEvent *G__Lderived;
     G__Lderived=(TEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TEventDictLN_TEvent),G__get_linked_tagnum(&G__TEventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TEventDictLN_IDet))) {
     IDet *G__Lderived;
     G__Lderived=(IDet*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TEventDictLN_IDet),G__get_linked_tagnum(&G__TEventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TEventDictLN_ITdc))) {
     ITdc *G__Lderived;
     G__Lderived=(ITdc*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TEventDictLN_ITdc),G__get_linked_tagnum(&G__TEventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTEventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__TEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__TEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__TEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__TEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__TEventDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TEvent */
static void G__setup_memvarTEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TEventDictLN_TEvent));
   { TEvent *p; p=(TEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fThetacm)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fThetacm=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fLP)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fLP=",0,"Light particle energy //");
   G__memvar_setup((void*)((long)(&p->fHP)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fHP=",0,"Heavy particle energy //");
   G__memvar_setup((void*)((long)(&p->fQv)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fQv=",0,"Q-value                   //");
   G__memvar_setup((void*)((long)(&p->fEB)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fEB=",0,"Beam energy           //");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fRun=",0,"Current run number");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* IDet */
static void G__setup_memvarIDet(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TEventDictLN_IDet));
   { IDet *p; p=(IDet*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->TYdMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TYdMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TYdChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdEnergy)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TYdEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdADC)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TYdADC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdNo)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TYdNo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdRing)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TYdRing=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdTheta)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TYdTheta=",0,"Yd theta angle");
   G__memvar_setup((void*)((long)(&p->TCsI1Mul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TCsI1Mul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TCsI1Channel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TCsI1Channel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TCsI1Energy)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TCsI1Energy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TCsI1ADC)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TCsI1ADC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TCsI2Mul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TCsI2Mul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TCsI2Channel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TCsI2Channel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TCsI2Energy)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TCsI2Energy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TCsI2ADC)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TCsI2ADC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SSB)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"SSB=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TICChannel)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TICChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TICEnergy)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TICEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TIC)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TIC[16]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1rMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSd1rMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1rChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TSd1rChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1rEnergy)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd1rEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1rADC)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TSd1rADC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1sMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSd1sMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1sChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TSd1sChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1sEnergy)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd1sEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1sADC)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TSd1sADC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2rMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSd2rMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2rChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TSd2rChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2rEnergy)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd2rEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2rADC)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TSd2rADC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2rEnergyCal)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TSd2rEnergyCal=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2sMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSd2sMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2sChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TSd2sChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2sEnergy)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd2sEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2sADC)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"TSd2sADC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSdETot)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TSdETot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSdTheta)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSdTheta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSdThetaCM)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TSdThetaCM=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSdPhi)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSdPhi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QValue)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"QValue=",0,"Q-value from YY1 and CsI2");
   G__memvar_setup((void*)((long)(&p->TBE)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TBE=",0,"Beam energy");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* ITdc */
static void G__setup_memvarITdc(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TEventDictLN_ITdc));
   { ITdc *p; p=(ITdc*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->TICTMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TICTMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TICTChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TICTChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TICTime)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TICTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TICTimeRF)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TICTimeRF=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdTMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TYdTMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdTChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TYdTChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdTime)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TYdTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYdTimeRF)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TYdTimeRF=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYuTMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TYuTMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYuTChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TYuTChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYuTime)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TYuTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TYuTimeRF)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TYuTimeRF=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSurTMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSurTMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSurTChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSurTChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSurTime)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSurTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSurTimeRF)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSurTimeRF=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSusTMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSusTMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSusTChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSusTChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSusTime)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSusTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSusTimeRF)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSusTimeRF=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1rTMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSd1rTMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1rTChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd1rTChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1rTime)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd1rTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1rTimeRF)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd1rTimeRF=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1sTMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSd1sTMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1sTChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd1sTChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1sTime)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd1sTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd1sTimeRF)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd1sTimeRF=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2rTMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSd2rTMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2rTChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd2rTChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2rTime)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd2rTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2rTimeRF)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd2rTimeRF=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2sTMul)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TSd2sTMul=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2sTChannel)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd2sTChannel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2sTime)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd2sTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TSd2sTimeRF)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"TSd2sTimeRF=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTEventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTEvent(void) {
   /* TEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TEventDictLN_TEvent));
   G__memfunc_setup("TEvent",598,G__TEventDict_548_0_1, 105, G__get_linked_tagnum(&G__TEventDictLN_TEvent), -1, 0, 0, 1, 1, 0, "", "! Create", (void*) NULL, 0);
   G__memfunc_setup("TEvent",598,G__TEventDict_548_0_2, 105, G__get_linked_tagnum(&G__TEventDictLN_TEvent), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - -", "!", (void*) NULL, 0);
   G__memfunc_setup("TEvent",598,G__TEventDict_548_0_3, 105, G__get_linked_tagnum(&G__TEventDictLN_TEvent), -1, 0, 1, 1, 1, 0, "u 'TEvent' - 11 - -", "!", (void*) NULL, 0);
   G__memfunc_setup("Calculate",910,G__TEventDict_548_0_4, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", "! Calculate derived variables", (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__TEventDict_548_0_5, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", "! Clear values", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TEventDict_548_0_6, 85, G__get_linked_tagnum(&G__TEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TEventDict_548_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TEventDict_548_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TEventDict_548_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TEventDict_548_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TEventDict_548_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TEventDict_548_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TEventDict_548_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TEventDict_548_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TEvent::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TEvent", 724, G__TEventDict_548_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TEventDict_548_0_19, (int) ('u'), G__get_linked_tagnum(&G__TEventDictLN_TEvent), -1, 1, 1, 1, 1, 0, "u 'TEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncIDet(void) {
   /* IDet */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TEventDictLN_IDet));
   G__memfunc_setup("IDet",358,G__TEventDict_549_0_1, 105, G__get_linked_tagnum(&G__TEventDictLN_IDet), -1, 0, 0, 1, 1, 0, "", "! Create", (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__TEventDict_549_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TEventDict_549_0_3, 85, G__get_linked_tagnum(&G__TEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&IDet::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TEventDict_549_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDet::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TEventDict_549_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&IDet::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TEventDict_549_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&IDet::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TEventDict_549_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TEventDict_549_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDet::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TEventDict_549_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IDet::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TEventDict_549_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDet::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TEventDict_549_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IDet::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("IDet", 358, G__TEventDict_549_0_15, (int) ('i'), G__get_linked_tagnum(&G__TEventDictLN_IDet), -1, 0, 1, 1, 1, 0, "u 'IDet' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~IDet", 484, G__TEventDict_549_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TEventDict_549_0_17, (int) ('u'), G__get_linked_tagnum(&G__TEventDictLN_IDet), -1, 1, 1, 1, 1, 0, "u 'IDet' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncITdc(void) {
   /* ITdc */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TEventDictLN_ITdc));
   G__memfunc_setup("ITdc",356,G__TEventDict_554_0_1, 105, G__get_linked_tagnum(&G__TEventDictLN_ITdc), -1, 0, 0, 1, 1, 0, "", "! Create", (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__TEventDict_554_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TEventDict_554_0_3, 85, G__get_linked_tagnum(&G__TEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ITdc::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TEventDict_554_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ITdc::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TEventDict_554_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ITdc::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TEventDict_554_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ITdc::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TEventDict_554_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TEventDict_554_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ITdc::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TEventDict_554_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ITdc::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TEventDict_554_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ITdc::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TEventDict_554_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ITdc::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("ITdc", 356, G__TEventDict_554_0_15, (int) ('i'), G__get_linked_tagnum(&G__TEventDictLN_ITdc), -1, 0, 1, 1, 1, 0, "u 'ITdc' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ITdc", 482, G__TEventDict_554_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TEventDict_554_0_17, (int) ('u'), G__get_linked_tagnum(&G__TEventDictLN_ITdc), -1, 1, 1, 1, 1, 0, "u 'ITdc' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTEventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTEventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTEventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TEventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_TEvent = { "TEvent" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_IDet = { "IDet" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TEventDictLN_ITdc = { "ITdc" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTEventDict() {
  G__TEventDictLN_TClass.tagnum = -1 ;
  G__TEventDictLN_TBuffer.tagnum = -1 ;
  G__TEventDictLN_TMemberInspector.tagnum = -1 ;
  G__TEventDictLN_TObject.tagnum = -1 ;
  G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__TEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__TEventDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TEventDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__TEventDictLN_TEvent.tagnum = -1 ;
  G__TEventDictLN_IDet.tagnum = -1 ;
  G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__TEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TEventDictLN_ITdc.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTEventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TEventDictLN_TEvent),sizeof(TEvent),-1,325376,"Version",G__setup_memvarTEvent,G__setup_memfuncTEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TEventDictLN_IDet),sizeof(IDet),-1,292096,(char*)NULL,G__setup_memvarIDet,G__setup_memfuncIDet);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TEventDictLN_ITdc),sizeof(ITdc),-1,292096,(char*)NULL,G__setup_memvarITdc,G__setup_memfuncITdc);
}
extern "C" void G__cpp_setupTEventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTEventDict()");
  G__set_cpp_environmentTEventDict();
  G__cpp_setup_tagtableTEventDict();

  G__cpp_setup_inheritanceTEventDict();

  G__cpp_setup_typetableTEventDict();

  G__cpp_setup_memvarTEventDict();

  G__cpp_setup_memfuncTEventDict();
  G__cpp_setup_globalTEventDict();
  G__cpp_setup_funcTEventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTEventDict();
  return;
}
class G__cpp_setup_initTEventDict {
  public:
    G__cpp_setup_initTEventDict() { G__add_setup_func("TEventDict",(G__incsetup)(&G__cpp_setupTEventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTEventDict() { G__remove_setup_func("TEventDict"); }
};
G__cpp_setup_initTEventDict G__cpp_setup_initializerTEventDict;

